"""
bulk_rename_and_header.py
Generated by config UI.

1. Renames files and/or folders under ROOT_PATH, adding PREFIX/SUFFIX.
2. Inserts a fixed comment at the top of every .py file's contents.

DRY_RUN = True below. Review the printed output before
setting DRY_RUN = False if you want a safety preview first.
"""

import os

# ---------------- CONFIGURATION ----------------

ROOT_PATH = "C:\\Users\\abhis\\Desktop\\code\\Hacker_Rank_Pyton"

RENAME_TARGETS = "both"        # "files", "folders", or "both"
PREFIX = "Abhishek_"
SUFFIX = "_done"
RENAME_FILE_EXTENSIONS = None      # e.g. [".py"] to limit which files get renamed
EXCLUDE_NAMES = {".git", "__pycache__", ".vscode", "venv", ".gitignore"}

ADD_HEADER = True
HEADER_COMMENT = """// Author: Abhishek_Kr
// Python for Data Science assignment"""
HEADER_MARKER = "// Author: Abhishek_Kr"

DRY_RUN = False

# -------------------------------------------------


def build_new_name(name, is_file):
    base, ext = os.path.splitext(name) if is_file else (name, "")
    return f"{PREFIX}{base}{SUFFIX}" + ext


def should_rename_file(filename):
    if RENAME_FILE_EXTENSIONS is None:
        return True
    return os.path.splitext(filename)[1] in RENAME_FILE_EXTENSIONS


def rename_all(root_path):
    changes = []
    for dirpath, dirnames, filenames in os.walk(root_path, topdown=False):
        if any(part in EXCLUDE_NAMES for part in dirpath.split(os.sep)):
            continue

        if RENAME_TARGETS in ("files", "both"):
            for fname in filenames:
                if fname in EXCLUDE_NAMES or not should_rename_file(fname):
                    continue
                old_path = os.path.join(dirpath, fname)
                new_path = os.path.join(dirpath, build_new_name(fname, True))
                if old_path != new_path:
                    changes.append((old_path, new_path))

        if RENAME_TARGETS in ("folders", "both"):
            for dname in dirnames:
                if dname in EXCLUDE_NAMES:
                    continue
                old_path = os.path.join(dirpath, dname)
                new_path = os.path.join(dirpath, build_new_name(dname, False))
                if old_path != new_path:
                    changes.append((old_path, new_path))

    for old_path, new_path in changes:
        print(f"{'[DRY RUN] ' if DRY_RUN else ''}RENAME: {old_path} -> {new_path}")
        if not DRY_RUN:
            os.rename(old_path, new_path)

    print(f"\n{len(changes)} rename operation(s) {'previewed' if DRY_RUN else 'completed'}.")


def insert_header_in_py_files(root_path):
    py_files = []
    for dirpath, dirnames, filenames in os.walk(root_path):
        dirnames[:] = [d for d in dirnames if d not in EXCLUDE_NAMES]
        for fname in filenames:
            if fname.endswith(".py"):
                py_files.append(os.path.join(dirpath, fname))

    updated = 0
    for filepath in py_files:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()

        if HEADER_MARKER in content:
            print(f"SKIP (already has header): {filepath}")
            continue

        lines = content.splitlines(keepends=True)
        insert_at = 1 if lines and lines[0].startswith("#!") else 0
        new_content = "".join(lines[:insert_at] + [HEADER_COMMENT + "\n\n"] + lines[insert_at:])

        print(f"{'[DRY RUN] ' if DRY_RUN else ''}ADD HEADER: {filepath}")
        if not DRY_RUN:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(new_content)
            updated += 1

    print(f"\n{len(py_files)} .py file(s) scanned, {updated if not DRY_RUN else 'N/A (dry run)'} updated.")


if __name__ == "__main__":
    print(f"=== Mode: {'DRY RUN' if DRY_RUN else 'LIVE - files will be modified'} ===\n")
    print("--- Step 1: Renaming files/folders ---")
    rename_all(ROOT_PATH)
    if ADD_HEADER:
        print("\n--- Step 2: Inserting header comments ---")
        insert_header_in_py_files(ROOT_PATH)
